
export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">

      <main className="container mx-auto px-6 py-20 max-w-4xl flex-1">
        <h1 className="text-5xl font-bold text-primary mb-8">Terms of Use</h1>

        <div className="space-y-8 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Lumiere, you accept and agree to be bound by the terms and provision of this
              agreement. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">2. Use of Service</h2>
            <p className="mb-4">
              Lumiere provides an AI-powered trading strategy platform. You agree to use the service only for lawful
              purposes and in accordance with these Terms of Use.
            </p>
            <p>
              You are responsible for maintaining the confidentiality of your wallet connection and for all activities
              that occur under your account.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">3. Trading Risks</h2>
            <p className="mb-4">
              Trading cryptocurrencies and other financial instruments involves substantial risk of loss. Past
              performance is not indicative of future results.
            </p>
            <p>
              You acknowledge that you are solely responsible for your trading decisions and that Lumiere does not
              provide financial advice. All strategies generated by Prophet AI are for informational purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">4. Intellectual Property</h2>
            <p>
              The service and its original content, features, and functionality are owned by Lumiere and are protected
              by international copyright, trademark, and other intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">5. Limitation of Liability</h2>
            <p>
              In no event shall Lumiere, nor its directors, employees, partners, agents, suppliers, or affiliates, be
              liable for any indirect, incidental, special, consequential, or punitive damages, including without
              limitation, loss of profits, data, use, goodwill, or other intangible losses.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">6. Changes to Terms</h2>
            <p>
              We reserve the right to modify or replace these terms at any time. If a revision is material, we will
              provide at least 30 days' notice prior to any new terms taking effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">7. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us through our official communication
              channels.
            </p>
          </section>
        </div>

        <div className="mt-12 p-6 rounded-lg border border-primary/20 bg-card/50">
          <p className="text-sm text-muted-foreground">
            Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </p>
        </div>
      </main>

    </div>
  )
}
